### ISSUE TITLE
Provider error on remote_replications modification

### ISSUE THREAD

**Issue by jeidsath** [jfrog/terraform-provider-artifactory#1105]
**Describe the bug**

Plan:
![Image](https://github.com/user-attachments/assets/c9b07211-ed9c-4ffe-b658-2b3f24ff9abc)

Apply:
![Image](https://github.com/user-attachments/assets/89c1da4e-03fe-49a7-b42a-860561e848c6)

These remote_replications are set to enabled = false. The plan change specified their cron_exp, which was previously null.

Terraform snippets:

replications.tf

```terraform
locals {
  reps = yamldecode(file("${path.module}/replications.yaml"))
}

resource "artifactory_remote_repository_replication" "remote_replications" {
  for_each = { for repo in local.reps.replications.pull : repo.key => repo }
  repo_key = each.value.key

  cron_exp                    = lookup(each.value, "cron_exp", "0 0 * * * ?")
  enabled                     = lookup(each.value, "enabled", true)
  enable_event_replication    = lookup(each.value, "enable_event_replication", true)
  include_path_prefix_pattern = lookup(each.value, "include_path_prefix_pattern", null)
  sync_deletes                = lookup(each.value, "sync_deletes", false)
  sync_properties             = lookup(each.value, "sync_properties", false)
}
```

replications.yaml (only failing entries shown):

```yaml
---
replications:
  pull:
  - key: chocolatey-remote
    cron_exp: "0 0 0 * * ?"
    enable_event_replication: false
    enabled: false
  - key: edge-extensions-local-testlab-remote
    cron_exp: "0 0 0 * * ?"
    enabled: false
    sync_deletes: true
    sync_properties: true
  - key: longhorn-helm-remote
    cron_exp: "0 0 0 * * ?"
    enable_event_replication: false
    enabled: false
  - key: opensearch-helm-remote
    cron_exp: "0 0 0 * * ?"
    enable_event_replication: false
    enabled: false
```

Artifactory: 7.90.14
Terraform: 1.9.0
Terraform provider: jfrog/artifactory 12.1.0

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
No provider errors on apply

**Additional context**
cron_exp was being updated on these four replications because they had been showing up in the plan code with values check_binary.../id/replication_key showing as "known after apply". These were the only replications where cron_exp was "null", so we hoped setting it would be a fix. No other replications had errors on the apply.
